// COPYRIGHT DASSAULT SYSTEMES YYYY
#ifndef IIDLInterfaceName_h
#define IIDLInterfaceName_h

// System Framework
#include "CATBaseUnknown.h"

// Export from this module
#ifndef ExportedByModuleName
#define ExportedByModuleName
#endif

// IID declaration
extern ExportedByModuleName IID IID_IIDLInterfaceName;

/**
 * @brief IIDLInterfaceName - IDL Interface
 * 
 * This interface is defined via IDL and generated by MIDL compiler.
 * 
 * IDL interfaces enable:
 * - Cross-language communication (C++/Java/C#)
 * - COM interface definition
 * - Late binding support
 * 
 * Generated files from .idl:
 * - IIDLInterfaceName.h  (C++ header)
 * - IIDLInterfaceName_i.c (IID definitions)
 * - IIDLInterfaceName_p.c (Proxy/Stub)
 */
class ExportedByModuleName IIDLInterfaceName : public CATBaseUnknown
{
    CATDeclareInterface;

public:
    /**
     * @brief Method description
     * @param iParam Input parameter
     * @param oParam Output parameter  
     * @return HRESULT S_OK on success
     */
    virtual HRESULT MethodName(const Type iParam, Type& oParam) = 0;
};

#endif
