#!/usr/bin/env python3
"""
CADE Documentation Generator
=============================
Auto-generate CAA project documentation from workspace analysis.

Outputs:
  - Architecture overview (Mermaid diagrams)
  - Module inventory with commands/interfaces
  - Dependency maps
  - Build configuration summary
  - API reference outline

Usage:
  python docgen.py D:/workspace              # Generate all docs
  python docgen.py D:/workspace --format md  # Markdown only
  python docgen.py D:/workspace --format html # HTML
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# Add skills
sys.path.insert(0, str(Path(__file__).parent))

from actions import ActionContext


def generate_all(workspace_path: str, output_dir: Optional[str] = None) -> dict:
    """
    Generate complete project documentation.

    Returns dict with generated file paths and content.
    """
    ctx = ActionContext(workspace_path)
    ctx.refresh()
    snapshot = ctx.snapshot

    output = Path(output_dir) if output_dir else Path(workspace_path) / "CADE_Docs"
    output.mkdir(parents=True, exist_ok=True)

    generated = {}

    # 1. Architecture overview
    arch_md = _generate_architecture_md(snapshot)
    (output / "ARCHITECTURE.md").write_text(arch_md, encoding="utf-8")
    generated["architecture"] = str(output / "ARCHITECTURE.md")

    # 2. Module inventory
    mod_md = _generate_module_inventory(snapshot)
    (output / "MODULES.md").write_text(mod_md, encoding="utf-8")
    generated["modules"] = str(output / "MODULES.md")

    # 3. Dependency map
    dep_md = _generate_dependency_map(snapshot)
    (output / "DEPENDENCIES.md").write_text(dep_md, encoding="utf-8")
    generated["dependencies"] = str(output / "DEPENDENCIES.md")

    # 4. Build summary
    build_md = _generate_build_summary(snapshot)
    (output / "BUILD.md").write_text(build_md, encoding="utf-8")
    generated["build"] = str(output / "BUILD.md")

    # 5. Index
    index_md = _generate_index(snapshot, generated)
    (output / "INDEX.md").write_text(index_md, encoding="utf-8")
    generated["index"] = str(output / "INDEX.md")

    return {
        "status": "ok",
        "output_dir": str(output),
        "generated": generated,
        "generated_at": datetime.now().isoformat(),
    }


# ─── Generators ───────────────────────────────────────────────────


def _generate_architecture_md(snapshot) -> str:
    """Generate architecture overview with Mermaid diagrams"""
    lines = [
        f"# CAA Project Architecture",
        f"",
        f"> Auto-generated by CADE | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
        f"## Overview",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
    ]

    total_mods = sum(len(fw.modules) for fw in snapshot.frameworks)
    total_cmds = len(snapshot.get_all_commands())
    total_ifaces = len(snapshot.get_all_interfaces())
    total_wbs = len(snapshot.get_all_workbenches())

    lines += [
        f"| Frameworks | {len(snapshot.frameworks)} |",
        f"| Modules | {total_mods} |",
        f"| Commands | {total_cmds} |",
        f"| Interfaces | {total_ifaces} |",
        f"| Workbenches | {total_wbs} |",
        f"",
    ]

    # Framework hierarchy diagram
    lines += ["## Framework Hierarchy", "", "```mermaid", "graph TD"]
    for fw in snapshot.frameworks:
        fw_id = fw.name.replace(".", "_").replace("-", "_")
        lines.append(f"    {fw_id}[{fw.name}]")
        for mod in fw.modules:
            mod_id = f"{fw_id}_{mod.name.replace('.', '_')}"
            lines.append(f"    {fw_id} --> {mod_id}[{mod.name}]")
            for cmd in mod.commands:
                cmd_id = f"{mod_id}_{cmd.name}"
                lines.append(f"    {mod_id} --> {cmd_id}[{cmd.name}]")
    lines += ["```", ""]

    # Dependency diagram
    if hasattr(snapshot, "visualize_dependencies"):
        lines += ["## Dependency Graph", "", "```mermaid"]
        lines.append(snapshot.visualize_dependencies())
        lines += ["```", ""]

    # Framework details
    for fw in snapshot.frameworks:
        lines += [f"## Framework: {fw.name}", ""]
        lines += [f"- **Path**: `{fw.path}`", f"- **Modules**: {len(fw.modules)}", ""]

        for mod in fw.modules:
            lines += [f"### Module: {mod.name}", ""]
            lines += [f"- **Path**: `{mod.path}`", ""]

            if mod.commands:
                lines += ["**Commands**:", ""]
                for cmd in mod.commands:
                    dialog_note = (
                        f" (with dialog: {cmd.dialog.name})" if cmd.dialog else ""
                    )
                    wb_note = f" [in {cmd.workbench.name}]" if cmd.workbench else ""
                    lines.append(f"- `{cmd.name}`{dialog_note}{wb_note}")
                lines.append("")

    return "\n".join(lines)


def _generate_module_inventory(snapshot) -> str:
    """Generate detailed module inventory"""
    lines = [
        f"# Module Inventory",
        f"",
        f"> Auto-generated by CADE | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
    ]

    for fw in snapshot.frameworks:
        for mod in fw.modules:
            lines += [f"## {mod.name}", ""]

            # Commands
            if mod.commands:
                lines += [
                    "### Commands",
                    "",
                    "| Name | Type | Dialog | Workbench |",
                    "|------|------|--------|-----------|",
                ]
                for cmd in mod.commands:
                    cmd_type = "Stateful" if cmd.is_stateful else "Simple"
                    dlg = cmd.dialog.name if cmd.dialog else "—"
                    wb = cmd.workbench.name if cmd.workbench else "—"
                    lines.append(f"| `{cmd.name}` | {cmd_type} | {dlg} | {wb} |")
                lines.append("")

            # Interfaces
            if mod.interfaces:
                lines += [
                    "### Interfaces",
                    "",
                    "| Name | IDL | Implemented By |",
                    "|------|-----|---------------|",
                ]
                for iface in mod.interfaces:
                    idl = "Yes" if iface.is_idl else "No"
                    impl = (
                        ", ".join(c.name for c in iface.implemented_by)
                        if iface.implemented_by
                        else "—"
                    )
                    lines.append(f"| `{iface.name}` | {idl} | {impl} |")
                lines.append("")

            # Components
            if mod.components:
                lines += [
                    "### Components",
                    "",
                    "| Name | Implements | Parent Class |",
                    "|------|-----------|-------------|",
                ]
                for comp in mod.components:
                    impls = (
                        ", ".join(i.name for i in comp.implements)
                        if comp.implements
                        else "—"
                    )
                    lines.append(f"| `{comp.name}` | {impls} | {comp.parent_class} |")
                lines.append("")

            # Imakefile
            if mod.imakefile and mod.imakefile.exists():
                lines += ["### Build Configuration", "", "```makefile"]
                lines.append(
                    mod.imakefile.read_text(encoding="utf-8", errors="replace")[:500]
                )
                lines += ["```", ""]

    return "\n".join(lines)


def _generate_dependency_map(snapshot) -> str:
    """Generate dependency relationship documentation"""
    lines = [
        f"# Dependency Map",
        f"",
        f"> Auto-generated by CADE | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
        f"## Command Dependencies",
        f"",
    ]

    all_cmds = snapshot.get_all_commands()

    if all_cmds:
        lines += [
            "| Command | Module | Dialog | Workbench | Files |",
            "|---------|--------|--------|-----------|-------|",
        ]
        for cmd in all_cmds:
            mod_name = cmd.module.name if cmd.module else "?"
            dlg = cmd.dialog.name if cmd.dialog else "—"
            wb = cmd.workbench.name if cmd.workbench else "—"
            files = len(cmd.all_files) if hasattr(cmd, "all_files") else "?"
            lines.append(f"| `{cmd.name}` | {mod_name} | {dlg} | {wb} | {files} |")
        lines.append("")

    # Workbench to commands
    all_wbs = snapshot.get_all_workbenches()
    if all_wbs:
        lines += ["## Workbench → Command Map", ""]
        for wb in all_wbs:
            lines.append(f"### {wb.name}")
            for cmd in wb.commands:
                lines.append(f"- `{cmd.name}`")
            lines.append("")

    # Dependency graph
    if hasattr(snapshot, "dependency_graph") and snapshot.dependency_graph:
        lines += ["## Full Dependency Graph", "", "```mermaid"]
        lines.append(snapshot.visualize_dependencies())
        lines += ["```", ""]

    return "\n".join(lines)


def _generate_build_summary(snapshot) -> str:
    """Generate build configuration summary"""
    lines = [
        f"# Build Configuration",
        f"",
        f"> Auto-generated by CADE | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
    ]

    for fw in snapshot.frameworks:
        lines += [f"## {fw.name}", ""]

        # IdentityCard
        ic = fw.identitycard_path()
        if ic.exists():
            lines += ["### IdentityCard", "", "```cpp"]
            lines.append(ic.read_text(encoding="utf-8", errors="replace")[:300])
            lines += ["```", ""]

        # Dictionary
        dico = fw.dictionary_path()
        if dico.exists():
            lines += ["### Dictionary", "", "```"]
            lines.append(dico.read_text(encoding="utf-8", errors="replace")[:500])
            lines += ["```", ""]

        # Module build configs
        for mod in fw.modules:
            imake = mod.imakefile_path()
            if imake.exists():
                lines += [f"### {mod.name}/Imakefile.mk", "", "```makefile"]
                lines.append(imake.read_text(encoding="utf-8", errors="replace")[:500])
                lines += ["```", ""]

    return "\n".join(lines)


def _generate_index(snapshot, generated: dict) -> str:
    """Generate documentation index"""
    files_list = "\n".join(
        f"- [{Path(v).name}]({Path(v).name})" for v in generated.values()
    )

    return f"""# CAA Project Documentation

> Auto-generated by CADE | {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Contents

{files_list}

## Quick Stats

| Metric | Value |
|--------|-------|
| Frameworks | {len(snapshot.frameworks)} |
| Modules | {sum(len(fw.modules) for fw in snapshot.frameworks)} |
| Commands | {len(snapshot.get_all_commands())} |
| Interfaces | {len(snapshot.get_all_interfaces())} |
| Workbenches | {len(snapshot.get_all_workbenches())} |
"""


# ─── CLI ──────────────────────────────────────────────────────────


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="CADE Documentation Generator")
    parser.add_argument("workspace", help="Workspace path")
    parser.add_argument(
        "--output", "-o", help="Output directory (default: <workspace>/CADE_Docs)"
    )
    parser.add_argument(
        "--format", default="md", choices=["md", "html"], help="Output format"
    )

    args = parser.parse_args()

    result = generate_all(args.workspace, args.output)
    print(f"Generated {len(result['generated'])} files in {result['output_dir']}")
    for name, path in result["generated"].items():
        print(f"  {name}: {path}")
